name: Delete Branch When Issue is Closed

on:
  issues:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Workflow is Triggered
        run: echo "The workflow has been triggered because an issue was closed."
