name: Close and Delete Branch on Issue Close

on:
  issues:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Delete branch
        run: |
          BRANCH_NAME="feature-${{ github.event.issue.id }}"
          echo "Deleting branch $BRANCH_NAME"
          git push origin --delete "$BRANCH_NAME"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
